name: Comprobando Fugas

on:
  push:
    branches:
      - master

jobs:
  check-leaks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Instala Gitleaks
      run: |
        curl -sSL https://github.com/zricethezav/gitleaks/releases/download/v8.2.0/gitleaks_8.2.0_linux_x64.tar.gz | tar -xz -C /usr/local/bin gitleaks

    - name: Comprueba si hay fugasy
      run: |
        gitleaks detect --source . -v

